In [1]:
print("Numpy")

Numpy


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
b=np.ones((2,2), dtype="int32")

In [7]:
b

array([[1, 1],
       [1, 1]])

In [8]:
np.linalg.det(b)

0.0

In [9]:
arr = np.array([[1,2,4,5],[8,7,9,10]])

In [10]:
print(arr)

[[ 1  2  4  5]
 [ 8  7  9 10]]


In [11]:
arr.shape

(2, 4)

In [12]:
arr_new = np.matrix.transpose(arr)

In [13]:
print(arr_new)

[[ 1  8]
 [ 2  7]
 [ 4  9]
 [ 5 10]]


In [14]:
id = np.identity(3, dtype ="int32")

In [15]:
print(id)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
print(np.linalg.det(id))

1.0


In [17]:
random_array = np.random.randint(1,10, size=(3,3))
random_decimal_array = np.random.rand(3,3)

In [18]:
print(random_array)
print(random_decimal_array)

[[5 9 3]
 [2 7 9]
 [1 3 3]]
[[0.74219061 0.68280304 0.51722344]
 [0.8529508  0.18263572 0.01361697]
 [0.28996628 0.8525112  0.61231796]]


In [19]:
random_array * random_decimal_array

array([[3.71095303, 6.14522734, 1.55167031],
       [1.70590161, 1.27845002, 0.12255277],
       [0.28996628, 2.55753359, 1.83695387]])

In [46]:
multiplied_array = np.matmul(random_array,random_decimal_array)
multiplied_array

array([[12.25740908,  7.61527023,  4.54562383],
       [10.06473331, 10.31665686,  6.64062731],
       [ 4.17094184,  3.78824378,  2.39502823]])

In [54]:
floored = np.array(np.floor(multiplied_array), dtype = "int32")
floored

array([[12,  7,  4],
       [10, 10,  6],
       [ 4,  3,  2]])

In [58]:
pip install jupyter_contrib_nbextensions

Note: you may need to restart the kernel to use updated packages.
